name: Package CD

on: push

jobs:
    lint-and-test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Using node 21
          uses: actions/setup-node@v3
          with:
            node-version: 21.x

        - name: Install deps
          run: npm ci

        - name: Linter
          run: npm run lint

        - name: Test
          run: npm run test
        
    publish:
        needs: [lint-and-test]
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        steps:
            - uses: actions/checkout@v4
            - name: Using node 21
              uses: actions/setup-node@v3
              with:
                node-version: 21.x

            - name: Checking if there is diff in src folder
              uses: technote-space/get-diff-action@v6
              with:
                PATTERNS: src/**/*.ts

            - name: Update version
              run: |
                git config --global user.name 'Matthieu BRAULT'
                git config --global user.email 'matthieu.brault1@gmail.com'
                npm version patch -m "[RELEASE] %s"
              if: env.GIT_DIFF
    
            - name: Install deps
              run: |
                npm ci
              if: env.GIT_DIFF

    
            - name: Build
              run: npm run build
              if: env.GIT_DIFF
    
            - name: Publishing on npm
              run: |
                npm run publish
                git push
              if: env.GIT_DIFF
              env:
                NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}